// <copyright file="AircraftTypesControllerTest.cs" company="APIMatic">
// Aviationstack.Tests
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Threading.Tasks;
using APIMatic.Core.Utilities;
using Aviationstack.Standard;
using Aviationstack.Standard.Controllers;
using Aviationstack.Standard.Exceptions;
using Aviationstack.Standard.Http.Client;
using Aviationstack.Standard.Http.Response;
using Aviationstack.Standard.Utilities;
using Newtonsoft.Json.Converters;
using NUnit.Framework;

namespace Aviationstack.Tests
{
    /// <summary>
    /// AircraftTypesControllerTest.
    /// </summary>
    [TestFixture]
    public class AircraftTypesControllerTest : ControllerTestBase
    {
        /// <summary>
        /// Controller instance (for all tests).
        /// </summary>
        private AircraftTypesController controller;

        /// <summary>
        /// Setup test class.
        /// </summary>
        [OneTimeSetUp]
        public void SetUpDerived()
        {
            this.controller = this.Client.AircraftTypesController;
        }

        /// <summary>
        /// Retrieve aircraft type data.
        /// </summary>
        /// <returns>A <see cref="Task"/> representing the asynchronous unit test.</returns>
        [Test]
        public async Task TestTestGetAircraftTypes()
        {
            // Parameters for the API call
            int? limit = 100;
            int? offset = 0;
            string iataCode = null;

            // Perform API call
            Standard.Models.AircraftTypeResponse result = null;
            try
            {
                result = await this.controller.GetAircraftTypesAsync(limit, offset, iataCode);
            }
            catch (ApiException)
            {
            }

            // Test response code
            Assert.AreEqual(200, HttpCallBack.Response.StatusCode, "Status should be 200");

            // Test headers
            Dictionary<string, string> headers = new Dictionary<string, string>();
            headers.Add("Content-Type", "application/json");

            Assert.IsTrue(
                    TestHelper.AreHeadersProperSubsetOf (
                    headers,
                    HttpCallBack.Response.Headers),
                    "Headers should match");
        }
    }
}