// <copyright file="FlightsControllerTest.cs" company="APIMatic">
// Aviationstack.Tests
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Threading.Tasks;
using APIMatic.Core.Utilities;
using Aviationstack.Standard;
using Aviationstack.Standard.Controllers;
using Aviationstack.Standard.Exceptions;
using Aviationstack.Standard.Http.Client;
using Aviationstack.Standard.Http.Response;
using Aviationstack.Standard.Utilities;
using Newtonsoft.Json.Converters;
using NUnit.Framework;

namespace Aviationstack.Tests
{
    /// <summary>
    /// FlightsControllerTest.
    /// </summary>
    [TestFixture]
    public class FlightsControllerTest : ControllerTestBase
    {
        /// <summary>
        /// Controller instance (for all tests).
        /// </summary>
        private FlightsController controller;

        /// <summary>
        /// Setup test class.
        /// </summary>
        [OneTimeSetUp]
        public void SetUpDerived()
        {
            this.controller = this.Client.FlightsController;
        }

        /// <summary>
        /// Retrieve real-time and historical flight data.
        /// </summary>
        /// <returns>A <see cref="Task"/> representing the asynchronous unit test.</returns>
        [Test]
        public async Task TestTestGetFlights()
        {
            // Parameters for the API call
            int? limit = 100;
            int? offset = 0;
            string flightIata = null;
            string flightIcao = null;
            string airlineIata = null;
            string airlineIcao = null;
            string flightNumber = null;
            string depIata = null;
            string depIcao = null;
            string arrIata = null;
            string arrIcao = null;
            Standard.Models.FlightStatus2Enum? flightStatus = null;
            DateTime? date = null;

            // Perform API call
            Standard.Models.FlightResponse result = null;
            try
            {
                result = await this.controller.GetFlightsAsync(limit, offset, flightIata, flightIcao, airlineIata, airlineIcao, flightNumber, depIata, depIcao, arrIata, arrIcao, flightStatus, date);
            }
            catch (ApiException)
            {
            }

            // Test response code
            Assert.AreEqual(200, HttpCallBack.Response.StatusCode, "Status should be 200");

            // Test headers
            Dictionary<string, string> headers = new Dictionary<string, string>();
            headers.Add("Content-Type", "application/json");

            Assert.IsTrue(
                    TestHelper.AreHeadersProperSubsetOf (
                    headers,
                    HttpCallBack.Response.Headers),
                    "Headers should match");
        }
    }
}