// <copyright file="IConfiguration.cs" company="APIMatic">
// Aviationstack.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System;
using System.Net;
using Aviationstack.Standard.Authentication;
using Aviationstack.Standard.Models;

namespace Aviationstack.Standard
{
    /// <summary>
    /// IConfiguration.
    /// </summary>
    public interface IConfiguration
    {
        /// <summary>
        /// Gets Current API environment.
        /// </summary>
        Environment Environment { get; }

        /// <summary>
        /// Gets the credentials to use with CustomQueryAuthentication.
        /// </summary>
        ICustomQueryAuthenticationCredentials CustomQueryAuthenticationCredentials { get; }

        /// <summary>
        /// Gets the credentials model to use with CustomQueryAuthentication.
        /// </summary>
        CustomQueryAuthenticationModel CustomQueryAuthenticationModel { get; }

        /// <summary>
        /// Gets the URL for a particular alias in the current environment and appends it with template parameters.
        /// </summary>
        /// <param name="alias">Default value:DEFAULT.</param>
        /// <returns>Returns the baseurl.</returns>
        string GetBaseUri(Server alias = Server.Default);
    }
}