// <copyright file="AirlineInfo.cs" company="APIMatic">
// Aviationstack.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using APIMatic.Core.Utilities.Converters;
using Aviationstack.Standard;
using Aviationstack.Standard.Utilities;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Aviationstack.Standard.Models
{
    /// <summary>
    /// AirlineInfo.
    /// </summary>
    public class AirlineInfo
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AirlineInfo"/> class.
        /// </summary>
        public AirlineInfo()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AirlineInfo"/> class.
        /// </summary>
        /// <param name="name">name.</param>
        /// <param name="iata">iata.</param>
        /// <param name="icao">icao.</param>
        public AirlineInfo(
            string name = null,
            string iata = null,
            string icao = null)
        {
            this.Name = name;
            this.Iata = iata;
            this.Icao = icao;
        }

        /// <summary>
        /// Airline name
        /// </summary>
        [JsonProperty("name", NullValueHandling = NullValueHandling.Ignore)]
        public string Name { get; set; }

        /// <summary>
        /// IATA code
        /// </summary>
        [JsonProperty("iata", NullValueHandling = NullValueHandling.Ignore)]
        public string Iata { get; set; }

        /// <summary>
        /// ICAO code
        /// </summary>
        [JsonProperty("icao", NullValueHandling = NullValueHandling.Ignore)]
        public string Icao { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"AirlineInfo : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is AirlineInfo other &&
                (this.Name == null && other.Name == null ||
                 this.Name?.Equals(other.Name) == true) &&
                (this.Iata == null && other.Iata == null ||
                 this.Iata?.Equals(other.Iata) == true) &&
                (this.Icao == null && other.Icao == null ||
                 this.Icao?.Equals(other.Icao) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Name = {this.Name ?? "null"}");
            toStringOutput.Add($"Iata = {this.Iata ?? "null"}");
            toStringOutput.Add($"Icao = {this.Icao ?? "null"}");
        }
    }
}