// <copyright file="City.cs" company="APIMatic">
// Aviationstack.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using APIMatic.Core.Utilities.Converters;
using Aviationstack.Standard;
using Aviationstack.Standard.Utilities;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Aviationstack.Standard.Models
{
    /// <summary>
    /// City.
    /// </summary>
    public class City
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="City"/> class.
        /// </summary>
        public City()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="City"/> class.
        /// </summary>
        /// <param name="cityName">city_name.</param>
        /// <param name="cityCode">city_code.</param>
        /// <param name="countryCode">country_code.</param>
        /// <param name="countryName">country_name.</param>
        public City(
            string cityName = null,
            string cityCode = null,
            string countryCode = null,
            string countryName = null)
        {
            this.CityName = cityName;
            this.CityCode = cityCode;
            this.CountryCode = countryCode;
            this.CountryName = countryName;
        }

        /// <summary>
        /// Name of the city
        /// </summary>
        [JsonProperty("city_name", NullValueHandling = NullValueHandling.Ignore)]
        public string CityName { get; set; }

        /// <summary>
        /// Code of the city
        /// </summary>
        [JsonProperty("city_code", NullValueHandling = NullValueHandling.Ignore)]
        public string CityCode { get; set; }

        /// <summary>
        /// Country code
        /// </summary>
        [JsonProperty("country_code", NullValueHandling = NullValueHandling.Ignore)]
        public string CountryCode { get; set; }

        /// <summary>
        /// Country name
        /// </summary>
        [JsonProperty("country_name", NullValueHandling = NullValueHandling.Ignore)]
        public string CountryName { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"City : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is City other &&
                (this.CityName == null && other.CityName == null ||
                 this.CityName?.Equals(other.CityName) == true) &&
                (this.CityCode == null && other.CityCode == null ||
                 this.CityCode?.Equals(other.CityCode) == true) &&
                (this.CountryCode == null && other.CountryCode == null ||
                 this.CountryCode?.Equals(other.CountryCode) == true) &&
                (this.CountryName == null && other.CountryName == null ||
                 this.CountryName?.Equals(other.CountryName) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"CityName = {this.CityName ?? "null"}");
            toStringOutput.Add($"CityCode = {this.CityCode ?? "null"}");
            toStringOutput.Add($"CountryCode = {this.CountryCode ?? "null"}");
            toStringOutput.Add($"CountryName = {this.CountryName ?? "null"}");
        }
    }
}