// <copyright file="FlightStatusEnum.cs" company="APIMatic">
// Aviationstack.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using APIMatic.Core.Utilities.Converters;
using Aviationstack.Standard;
using Aviationstack.Standard.Utilities;
using Newtonsoft.Json;

namespace Aviationstack.Standard.Models
{
    /// <summary>
    /// FlightStatusEnum.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum FlightStatusEnum
    {
        /// <summary>
        /// Scheduled.
        /// </summary>
        [EnumMember(Value = "scheduled")]
        Scheduled,

        /// <summary>
        /// Active.
        /// </summary>
        [EnumMember(Value = "active")]
        Active,

        /// <summary>
        /// Landed.
        /// </summary>
        [EnumMember(Value = "landed")]
        Landed,

        /// <summary>
        /// Cancelled.
        /// </summary>
        [EnumMember(Value = "cancelled")]
        Cancelled,

        /// <summary>
        /// Incident.
        /// </summary>
        [EnumMember(Value = "incident")]
        Incident,

        /// <summary>
        /// Diverted.
        /// </summary>
        [EnumMember(Value = "diverted")]
        Diverted
    }
}