// <copyright file="FlightInfo.cs" company="APIMatic">
// Aviationstack.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using APIMatic.Core.Utilities.Converters;
using Aviationstack.Standard;
using Aviationstack.Standard.Utilities;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Aviationstack.Standard.Models
{
    /// <summary>
    /// FlightInfo.
    /// </summary>
    public class FlightInfo
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FlightInfo"/> class.
        /// </summary>
        public FlightInfo()
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="FlightInfo"/> class.
        /// </summary>
        /// <param name="number">number.</param>
        /// <param name="iata">iata.</param>
        /// <param name="icao">icao.</param>
        /// <param name="codeshared">codeshared.</param>
        public FlightInfo(
            string number = null,
            string iata = null,
            string icao = null,
            string codeshared = null)
        {
            this.Number = number;
            this.Iata = iata;
            this.Icao = icao;
            this.Codeshared = codeshared;
        }

        /// <summary>
        /// Flight number
        /// </summary>
        [JsonProperty("number", NullValueHandling = NullValueHandling.Ignore)]
        public string Number { get; set; }

        /// <summary>
        /// IATA code
        /// </summary>
        [JsonProperty("iata", NullValueHandling = NullValueHandling.Ignore)]
        public string Iata { get; set; }

        /// <summary>
        /// ICAO code
        /// </summary>
        [JsonProperty("icao", NullValueHandling = NullValueHandling.Ignore)]
        public string Icao { get; set; }

        /// <summary>
        /// Codeshare information
        /// </summary>
        [JsonProperty("codeshared", NullValueHandling = NullValueHandling.Ignore)]
        public string Codeshared { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"FlightInfo : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is FlightInfo other &&
                (this.Number == null && other.Number == null ||
                 this.Number?.Equals(other.Number) == true) &&
                (this.Iata == null && other.Iata == null ||
                 this.Iata?.Equals(other.Iata) == true) &&
                (this.Icao == null && other.Icao == null ||
                 this.Icao?.Equals(other.Icao) == true) &&
                (this.Codeshared == null && other.Codeshared == null ||
                 this.Codeshared?.Equals(other.Codeshared) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Number = {this.Number ?? "null"}");
            toStringOutput.Add($"Iata = {this.Iata ?? "null"}");
            toStringOutput.Add($"Icao = {this.Icao ?? "null"}");
            toStringOutput.Add($"Codeshared = {this.Codeshared ?? "null"}");
        }
    }
}