// <copyright file="TypeEnum.cs" company="APIMatic">
// Aviationstack.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using APIMatic.Core.Utilities.Converters;
using Aviationstack.Standard;
using Aviationstack.Standard.Utilities;
using Newtonsoft.Json;

namespace Aviationstack.Standard.Models
{
    /// <summary>
    /// TypeEnum.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum TypeEnum
    {
        /// <summary>
        /// Departure.
        /// </summary>
        [EnumMember(Value = "departure")]
        Departure,

        /// <summary>
        /// Arrival.
        /// </summary>
        [EnumMember(Value = "arrival")]
        Arrival
    }
}