// <copyright file="CustomQueryAuthenticationManager.cs" company="APIMatic">
// Aviationstack.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Aviationstack.Standard.Http.Request;
using APIMatic.Core.Authentication;

namespace Aviationstack.Standard.Authentication
{
    /// <summary>
    /// CustomQueryAuthenticationManager.
    /// </summary>
    internal class CustomQueryAuthenticationManager : AuthManager, ICustomQueryAuthenticationCredentials
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CustomQueryAuthenticationManager"/> class.
        /// </summary>
        /// <param name="customQueryAuthentication">CustomQueryAuthenticationModel.</param>
        internal CustomQueryAuthenticationManager(CustomQueryAuthenticationModel customQueryAuthentication)
        {
            AccessKey = customQueryAuthentication?.AccessKey;
            Parameters(paramBuilder => paramBuilder
                .Query(query => query.Setup("access_key", AccessKey).Required())
            );
        }

        /// <summary>
        /// Gets string value for accessKey.
        /// </summary>
        public string AccessKey { get; }

        /// <summary>
        /// Check if credentials match.
        /// </summary>
        /// <param name="accessKey"> The string value for credentials.</param>
        /// <returns> True if credentials matched.</returns>
        public bool Equals(string accessKey)
        {
            return accessKey.Equals(this.AccessKey);
        }
    }

    public sealed class CustomQueryAuthenticationModel
    {
        internal CustomQueryAuthenticationModel()
        {
        }

        internal string AccessKey { get; set; }

        /// <summary>
        /// Creates an object of the CustomQueryAuthenticationModel using the values provided for the builder.
        /// </summary>
        /// <returns>Builder.</returns>
        public Builder ToBuilder()
        {
            return new Builder(AccessKey);
        }

        /// <summary>
        /// Builder class for CustomQueryAuthenticationModel.
        /// </summary>
        public class Builder
        {
            private string accessKey;

            public Builder(string accessKey)
            {
                this.accessKey = accessKey ?? throw new ArgumentNullException(nameof(accessKey));
            }

            /// <summary>
            /// Sets AccessKey.
            /// </summary>
            /// <param name="accessKey">AccessKey.</param>
            /// <returns>Builder.</returns>
            public Builder AccessKey(string accessKey)
            {
                this.accessKey = accessKey ?? throw new ArgumentNullException(nameof(accessKey));
                return this;
            }

            /// <summary>
            /// Creates an object of the CustomQueryAuthenticationModel using the values provided for the builder.
            /// </summary>
            /// <returns>CustomQueryAuthenticationModel.</returns>
            public CustomQueryAuthenticationModel Build()
            {
                return new CustomQueryAuthenticationModel()
                {
                    AccessKey = this.accessKey
                };
            }
        }
    }
}
