// <copyright file="ICustomQueryAuthenticationCredentials.cs" company="APIMatic">
// Aviationstack.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using System;

namespace Aviationstack.Standard.Authentication
{
    /// <summary>
    /// Authentication configuration interface for CustomQueryAuthentication.
    /// </summary>
    public interface ICustomQueryAuthenticationCredentials
    {
        /// <summary>
        /// Gets string value for accessKey.
        /// </summary>
        string AccessKey { get; }

        /// <summary>
        ///  Returns true if credentials matched.
        /// </summary>
        /// <param name="accessKey"> The string value for credentials.</param>
        /// <returns>True if credentials matched.</returns>
        bool Equals(string accessKey);
    }
}